# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

auctionbf2cpp <- function(d, n, pers_to_obj, obj_to_pers, price, profit, neps, epsvec) {
    .Call(`_ttbary_auctionbf2cpp`, d, n, pers_to_obj, obj_to_pers, price, profit, neps, epsvec)
}

optimClusterCenterEuclid2 <- function(clustx, clusty, centerx, centery) {
    invisible(.Call(`_ttbary_optimClusterCenterEuclid2`, clustx, clusty, centerx, centery))
}

kMeansBary <- function(zetax, zetay, ppmatx, ppmaty, penalty, add_del = 1e4L, N = 200L, eps = 0.001, exact = FALSE, verbose = 0L) {
    .Call(`_ttbary_kMeansBary`, zetax, zetay, ppmatx, ppmaty, penalty, add_del, N, eps, exact, verbose)
}

sampleFromData <- function(n, ppvecx, ppvecy) {
    .Call(`_ttbary_sampleFromData`, n, ppvecx, ppvecy)
}

kMeansBaryEps <- function(epsvec, zetax, zetay, ppmatx, ppmaty, penalty, add_del = 1e4L, relaxationVars = as.integer( c(3,1,2,2)), N = 200L, eps = 0.001, exact = FALSE, verbose = 0L) {
    .Call(`_ttbary_kMeansBaryEps`, epsvec, zetax, zetay, ppmatx, ppmaty, penalty, add_del, relaxationVars, N, eps, exact, verbose)
}

DreznerEuclid2 <- function(clustx, clusty, penp, reduction, aleph) {
    .Call(`_ttbary_DreznerEuclid2`, clustx, clusty, penp, reduction, aleph)
}

heuristicCenter2 <- function(clustx, clusty, centerx, centery, penp, bounds) {
    .Call(`_ttbary_heuristicCenter2`, clustx, clusty, centerx, centery, penp, bounds)
}

kMeansBaryNet <- function(dpath, zeta, ppmat, penalty, add_del = 1e4L, N = 200L, eps = 0.001) {
    .Call(`_ttbary_kMeansBaryNet`, dpath, zeta, ppmat, penalty, add_del, N, eps)
}

